### PR TITLE
fix typos in code scripts

### PR DESCRIPTION
**Pull request by Vad1mo**
While executing the ADF, I stumbled upon some typos.

*Description of changes:*

In the Scripts examples there are a few missing Shell Parameter Expansion aka.`$` 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Vad1mo** [comment]
thx @klontje85

**Comment by bundyfx** [comment]
Thanks for the PR! - We are reworking the installation steps as we move ADF into the Serverless Application Repository (SAR). From 1.0.0 onwards installation and updates will be single click from the SAR.

**Comment by Vad1mo** [comment]
@bundyfx @klontje85 when do you plan to release 1.0.0 as part of SAR?
You can also reach me via PN.

**Comment by iheshes** [comment]
@bundyfx Any ETA for 1.0.0 release?

**Pull request closed without merging**
