### PR TITLE
fix: do not add duplicate inputs

### PR DESCRIPTION
**Pull request by Nr18**
*Issue #, if available:* #445

*Description of changes:*

When using the `param_overrides` functionality. And you use 2 parameters from the same source. The artifact is added twice to the action. This causes the pipeline to fail.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by sbkok — CHANGES_REQUESTED** [review]
Thanks for providing a fix for this issue.

Could you please add test cases to the following file [0] to verify that this works correctly?
That way we know it will continue to work in the future, even if this part gets refactored.

* [0] https://github.com/awslabs/aws-deployment-framework/blob/0723ddf4eaf55888ae780dc48873f0ec4766cfbd/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/test_adf_codepipeline_input_artifacts.py

**Comment by Nr18** [comment]
@sbkok I added 2 tests:
* 1 to make sure that inputs are not added twice (the original fix)
* 2 when using different inputs it should be added.

Also added some context on how to run the top build locally.

**Review by sbkok — APPROVED** [review]
LGTM, thanks for adding the tests too.

**Review by javydekoning — APPROVED** [review]
Manually ran our latest CI on this. All checks are passing.

PR LGTM! Thanks for contributing.

**Pull request merged**
