### PR TITLE
Implement GitHub Actions

### PR DESCRIPTION
**Pull request by javydekoning**
*Issue #, if available:*
N/A

*Description of changes:*
Implement GitHub Actions to Replace Travis.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by javydekoning** [comment]
Had to loosen the version dependency for `sam-cli` to fix dependency conflicts. This results in a version bump for that package. 

Tested the CI in my fork.: 

```
============================== 19 passed in 1.28s ==============================
py39 run-test: commands[1] | make lint
# Linter performs static analysis to catch latent bugs
find src/ -iname "*.py" -not -path "src/.aws-sam/*" | xargs pylint --rcfile .pylintrc

------------------------------------
Your code has been rated at 10.00/10

cfn-lint
___________________________________ summary ____________________________________
  py39: commands succeeded
  congratulations :)
```

**Comment by javydekoning** [comment]
image

**Review by sbkok — APPROVED** [review]
Thank you!

**Review by StewartW — APPROVED** [review]
LGTM - Thanks

**Pull request merged**
