### PR TITLE
Fix: Added pipefail option so tee is not masking errors anymore

### PR DESCRIPTION
**Pull request by igordust**
# Why?

This fixes issue #642 

## What?

Description of changes:

terraform `plan command` is piped to `tee`, so errors occurring during the plan were masked.
I added pipefail option around terraform plan so that the scripts interrupts the execution and correctly report errors.

---

By submitting this pull request, I confirm that you can use, modify, copy, and
redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by sbkok — APPROVED** [review]
Thanks for diving into this and fixing the root cause.
Looks good to me!

**Review by javydekoning — APPROVED** [review]
Thanks! Good catch, I was looking into this and thought this was already handled by `set -e`, didn't spot the `tee` :)

**Comment by javydekoning** [comment]
Running CI before merge.

**Comment by javydekoning** [comment]
Need to fix #644 , for linter to pass.

**Pull request merged**
