### PR TITLE
Move account process to main SAR template

### PR DESCRIPTION
**Pull request by sbkok**
**Why?**

The SAR does not understand local references as introduced by the `src/account_processing.yml` unfortunately.

**What?**

After investigating several options, the only option that was accepted was to move the logic inside the main template instead. The references are updated to use the ones available in the main template directly.

Additionally, the ARN references are updated to include the partition correctly.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by StewartW** [comment]
Makes sense. 
Shame that sam publish and sam deploy have different reactions to this :(

**Review by StewartW — DISMISSED** [review]

**Comment by sbkok** [comment]
(Rebased on the latest commit in master to resolve a conflict)

**Review by StewartW — DISMISSED** [review]

**Review by javydekoning — DISMISSED** [review]
Thanks, LGTM!

**Comment by sbkok** [comment]
@javydekoning and @StewartW, I had to resolve a merge conflict. Unfortunately that dismissed the review approvals.

**Review by StewartW — APPROVED** [review]

**Pull request merged**
